[BetaFPV_SuperX_Nano]
extends = esp32_base
board = esp32-c3-devkitm-1
build_flags =
  ${esp32_base.build_flags}
  -I variants/betafpv_superx_nano
  ; -D ESP32_CPU_FREQ=80
  -D P_LORA_TX_NEOPIXEL_LED=19
  ; -D P_LORA_NSS=7
  ; -D P_LORA_DIO_1=18
  ; -D P_LORA_RESET=10
  ; -D P_LORA_BUSY=8
  -D P_LORA_NSS=0
  -D P_LORA_DIO_1=1
  -D P_LORA_RESET=2
  -D P_LORA_BUSY=3
  -D P_LORA_MOSI=4
  -D P_LORA_MISO=5
  -D P_LORA_SCLK=6
  -D SERIAL_RX=20
  -D SERIAL_TX=21
  
  -D PIN_USER_BTN=9
  
  -D LORA_TX_POWER=10

  ; -D NO_GLOBAL_SERIAL
  -D ARDUINO_USB_CDC_ON_BOOT=0
  ; -D CORE_DEBUG_LEVEL=0

  
  -D RADIO_CLASS=CustomLR1121
  -D WRAPPER_CLASS=CustomLR1121Wrapper
  -D RF_SWITCH_TABLE
  -D LR11X0_DIO_AS_RF_SWITCH=false
  -D LR11X0_DIO3_TCXO_VOLTAGE=0.0
  -D LR11X0_DCDC_ENABLE=true
  ; -D LR11X0_CURRENT_LIMIT=140
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/betafpv_superx_nano>

[env:BetaFPV_SuperX_Nano_repeater]
extends = BetaFPV_SuperX_Nano
build_src_filter = ${BetaFPV_SuperX_Nano.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
build_flags =
  ${BetaFPV_SuperX_Nano.build_flags}
  -D ADVERT_NAME='"SuperX Nano Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
 -D MESH_PACKET_LOGGING=1
 -D MESH_DEBUG=1
lib_deps =
  ${BetaFPV_SuperX_Nano.lib_deps}
  ${esp32_ota.lib_deps}

[env:BetaFPV_SuperX_Nano_companion_radio_serial]
extends = BetaFPV_SuperX_Nano
build_flags =
  ${BetaFPV_SuperX_Nano.build_flags}
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${BetaFPV_SuperX_Nano.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${BetaFPV_SuperX_Nano.lib_deps}
  densaugeo/base64 @ ~1.4.0
